version: "2"
networks:
  gitea:
services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    #restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
  drone-server:
    image: drone/drone:1.0.0-rc.1
    ports:
      - 80:80
      - 443:443
      #- 8000:8000
      #- 9000:9000
    networks:
      - gitea
    volumes:
      - ./drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    #restart: always
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      #- DRONE_RPC_SECRET=9c3921e3e748aff725d2e16ef31fbc42
      #- DRONE_USER_CREATE=username:xackery,machine:false,admin:true,token:a75febd2cc97c3cce9d98d4a8e8336d6